spring:
  application:
    name: prova

  datasource:
    url: jdbc:mariadb://localhost:3306/prova_arq_web
    username: root
    password: 
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect
